[package]
name = "file_monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.20", features = ["derive"] }
shellexpand = "3.1.0"
tokio = { version = "1.40.0", features = ["full"] }
tokio-io = "0.1.13"
walkdir = "2.5.0"
